trigger:
  - master
  - develop

pool: Default
#container: devopsinfra/docker-terragrunt

stages:
  - stage: Ansible
    displayName: 'AzureDevOps'
    jobs:
      - job: run_ansible_container
        steps:
          - script: |
              az container start --resource_group oso-production-resources --name oso-devops-cp-ansible
              az container attach --resource_group oso-production-resources --name oso-devops-cp-ansible
            displayName: 'ansible'
