trigger:
  - master
  - develop

pool: Default
#container: devopsinfra/docker-terragrunt

stages:
  - stage: AzureDevOps
    displayName: 'AzureDevOps'
    dependsOn: build
    jobs:
      - job: terraform_plan_azure_devops
        steps:
          - script: |
              cd azuredevops
              terragrunt plan
            displayName: 'terraform plan'
      - job: waitForValidation
        dependsOn: terraform_plan_azure_devops
        displayName: Wait for external validation
        pool: server
        timeoutInMinutes: 4320 # job times out in 3 days
        steps:
          - task: ManualValidation@0
            timeoutInMinutes: 1440 # task times out in 1 day
            inputs:
              notifyUsers: |
                mccullya@gmail.com
              instructions: 'Please validate the build configuration and resume'
              onTimeout: 'reject'
      - job: terraform_apply_azure_devops
        dependsOn: waitForValidation
        steps:
          - script: |
              cd azuredevops
              terragrunt apply -auto-approve
            displayName: 'terraform apply'